<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUALxp1U\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUALxp1U/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUALxp1U.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUALxp1U\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUALxp1U\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UALxp1U',
    'container.build_id' => '3e4fecaf',
    'container.build_time' => 1593753701,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUALxp1U');
