<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQtIzn8w\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQtIzn8w/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQtIzn8w.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQtIzn8w\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQtIzn8w\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QtIzn8w',
    'container.build_id' => 'f48289d8',
    'container.build_time' => 1594490191,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQtIzn8w');
