<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQK3ZOk0\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQK3ZOk0/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQK3ZOk0.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQK3ZOk0\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQK3ZOk0\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QK3ZOk0',
    'container.build_id' => '0fcaf37f',
    'container.build_time' => 1592065213,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQK3ZOk0');
